#公网IP：118.25.139.238

server:
  port: 8080
  servlet:
    context-path: /grocery-shop

datasource:
  test:
    jdbc-url: jdbc:mysql://118.25.139.238:3306/test?useSSL=false
    username: root
    password: zy514520
    driver-class-name: com.mysql.jdbc.Driver
  test2:
    jdbc-url: jdbc:mysql://118.25.139.238:3306/test2?useSSL=false
    username: root
    password: zy514520
    driver-class-name: com.mysql.jdbc.Driver

logging:
  path: /usr/own-develop/logs
  level:
    root: debug
    org:
      springframework:
        web: debug
